#!/usr/bin/env bash
#Now that you’ve parsed the Apache log file, let’s sort the data so you can get a better idea of what is going on.
filename="apache-access.log"

awk '{ print $1, $9 }' < $filename | sort | uniq -c | sort -rn 
