#!/usr/bin/env bash
# displaying Best School 10 times, but  for the 9th iteration, displays Best School and then Hi on a new line. You must use the while loop and if statement
i=0
while [ $i -le 10 ]
do
	if [ $i -eq 9]
	then	
		echo "Hi"
	fi
	i=$((i +))
done
