#!/usr/bin/env bash
#Best School 10 times,9th displays hi on new line,while&if

counter=1

while [ $counter -le 10 ]; do
	  if [ $counter -eq 9 ]; then
		      echo "Best School"
		          echo "Hi"
			    else
				        echo "Best School"
					  fi

					    ((counter++))
				    done

