#!/usr/bin/env bash
# displaying Best School 10 times, but  for the 9th iteration, displays Best School and then Hi on a new line. You must use the while loop and if statement
x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if [ $x -eq 9]
	then	
		echo "Hi"
	fi
	((x++))
done
